version: "3.9"
services:
    database:
        image: postgres:14.5
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: laravel-api
        ports:
            - "5432:5432"
        volumes:
            - "database:/var/lib/postgresql/data"
    application:
        build:
            context: .
        x-develop:
            watch:
                -   action: sync
                    path: .
                    target: /var/www
        ports:
            - "8000:80"
        depends_on:
            - database
volumes:
    database:
